import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} scroll-smooth focus:scroll-auto`}
    >
      <body className="bg-gray-300 min-h-screen w-full flex flex-col">
        <div className="h-14 text-white flex items-center">
          <Navbar />
        </div>
        <div className="flex-1 md:pt-3 flex flex-col md:flex-row overflow-hidden">
          <div
            id="guide-inner-content"
            className={`fixed bottom-0 w-full h-12 md:static md:w-20 lg:w-60 md:h-full lg:h-full lg:hover:overflow-y-auto transition-all duration-300 bg-lt-gradient bg-ltBackground text-ltColor dark:bg-drBackground dark:bg-dr-gradient dark:text-[#f8e9e9]`}
          >
            <Sidebar />
          </div>

          <div className="flex-1 bg-gray-300">{children}</div>
        </div>
      </body>
    </html>
  );
}
/* 

*/
