import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/side-bar/sidebar";
import StoreProvider from "./StoreProvider";
import AppSideBar from "@/components/side-bar/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} scroll-smooth focus:scroll-auto`}
    >
      <body className="bg-gray-300 ">
        <StoreProvider>
          <div className="min-h-screen w-full flex flex-col gap-2">
            <header className="h-14 text-white flex items-center relative z-10">
              <Navbar />
            </header>
            <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
              <AppSideBar />
              <main className="flex-1 bg-gray-300 overflow-hidden relative">
                {children}
              </main>
            </div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
/* 

*/
