import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} scroll-smooth focus:scroll-auto`}
    >
      <body className="bg-gray-300 h-screen w-screen flex flex-col">
        <div className="h-14 text-white flex items-center relative">
          <Navbar />
        </div>
        <div className="flex-1">
          <div className="flex h-full w-full md:flex-row flex-col overflow-hidden">
            <div
              id="guide-inner-content"
              className={`fixed w-full h-12 bottom-0 md:w-20 md:left-0 md:static 
                md:h-full  lg:w-60 lg:h-full lg:hover:overflow-y-auto 
                transition-all duration-300 bg-lt-gradient bg-ltBackground text-ltColor dark:bg-drBackground
                  dark:bg-dr-gradient Background dark:text-[#f8e9e9] `}
            >
              <Sidebar />
            </div>

            <div className="flex-1 bg-gray-300  ">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
